import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AnalyticsService } from './analyticsService';

export class ReportService {
  static addZeroBinLogo(doc) {
    // Add ZeroBin logo
    doc.setFillColor(16, 185, 129);
    doc.rect(14, 10, 12, 12, 'F');
    
    doc.setFillColor(255, 255, 255);
    doc.rect(16, 14, 8, 6, 'F');
    doc.rect(15, 13, 10, 1, 'F');
    doc.rect(18, 12, 4, 1, 'F');
    doc.rect(15, 15, 1, 3, 'F');
    doc.rect(24, 15, 1, 3, 'F');
    doc.rect(15, 20, 10, 1, 'F');
    
    doc.setFillColor(45, 212, 191);
    doc.circle(24, 20, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("0", 24, 22);
  }

  static addHeader(doc, reportType) {
    // Header
    doc.setTextColor(16, 185, 129);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("ZeroBin", 30, 20);
    
    doc.setTextColor(107, 114, 128);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Admin Portal", 30, 25);

    doc.setTextColor(30, 64, 175);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(`${reportType} Analytics Report`, 14, 40);

    doc.setTextColor(75, 85, 99);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 50);
  }

  static addFooter(doc) {
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.line(14, pageHeight - 20, pageWidth - 14, pageHeight - 20);
    
    doc.setTextColor(107, 114, 128);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("ZeroBin Admin Portal - Analytics System", 14, pageHeight - 10);
    
    const userInfo = localStorage.getItem('userInfo');
    const adminEmail = userInfo ? JSON.parse(userInfo).email : 'admin@zerobin.com';
    doc.text(`Generated by ZeroBin ${adminEmail}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
  }

  static generateSensorDataReport(doc, analytics) {
    const sensorData = [
      ['Total Bins', analytics.totalBins.toString()],
      ['Bins with Sensors', analytics.binsWithSensors.toString()],
      ['Average Fill Level', `${analytics.averageFill}%`],
      ['Critical Bins (90%+)', analytics.criticalBins.toString()],
      ['High Fill (75-89%)', analytics.highFillBins.toString()],
      ['Medium Fill (50-74%)', analytics.mediumFillBins.toString()],
      ['Low Fill (<50%)', analytics.lowFillBins.toString()]
    ];

    autoTable(doc, {
      startY: 60,
      head: [['Metric', 'Value']],
      body: sensorData,
      theme: "grid",
      headStyles: { 
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      styles: {
        fontSize: 10,
        cellPadding: 4
      }
    });
  }

  static generateAreaAnalysisReport(doc, areaAnalytics) {
    const areaData = areaAnalytics.map(area => [
      area.name,
      area.totalBins.toString(),
      area.sensorBins.toString(),
      `${area.averageFill}%`,
      area.criticalBins.toString(),
      area.priority
    ]);

    autoTable(doc, {
      startY: 60,
      head: [['Area', 'Total Bins', 'Sensor Bins', 'Avg Fill', 'Critical', 'Priority']],
      body: areaData,
      theme: "grid",
      headStyles: { 
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      styles: {
        fontSize: 9,
        cellPadding: 3
      }
    });
  }

  static generateReport(reportType, analytics, areaAnalytics) {
    const doc = new jsPDF();
    
    this.addZeroBinLogo(doc);
    this.addHeader(doc, reportType);
    
    if (reportType === 'Sensor Data') {
      this.generateSensorDataReport(doc, analytics);
    } else if (reportType === 'Area Analysis') {
      this.generateAreaAnalysisReport(doc, areaAnalytics);
    }
    
    this.addFooter(doc);
    
    const generatedDate = new Date().toLocaleDateString().replace(/\//g, "-");
    doc.save(`${reportType}_Analytics_${generatedDate}.pdf`);
    
    return `${reportType} report generated successfully!`;
  }
}
